### PR TITLE
Allow install on PHP8

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
This PR need support for laminas PHP8 support first.

**Comment by roelvanduijnhoven** [comment]
@snapshotpl I noticed a lot of new Laminas release: could you re-test your PR? If so: let me know, and I'll happily merge your PR.

**Comment by snapshotpl** [comment]
Mvc and servicemanager still waiting for php 8 support.

**Comment by NielsdeBlaauw** [comment]
Hi @snapshotpl 

With the release of servicemanager: 3.6.0 and mvc:3.2.0,  PHP8 support is available for all required packages. The current version constraints in this PR should permit all packages to update to a php8 compatible version.

Would you reconsider merging this PR?

Cheers.

**Comment by roelvanduijnhoven** [comment]
@NielsdeBlaauw and @snapshotpl It looks like we can release a PHP 8.x compatible version :).

Before we merge: can you update the .travis.yml file so that the TravisCI file does not show failure when the nightly fails? Apart from that it looks good to be merged!

Please ping me whenever this is ready to go, and I'll make sure to merge and release a new version. I guess this can be a minor release as the PHP version was not bumped?

**Comment by snapshotpl** [comment]
Looks like we need support php 8 for https://github.com/aws/aws-sdk-php-zf2 :-(

**Comment by roelvanduijnhoven** [comment]
Mm @snapshotpl I am looking _how_ we use that library. Actually we don't depend on it that hard. And it is an optional dependency.

You will find that only the test code uses `AwsModule`. The only requirement really is if you look at https://github.com/JouwWeb/SlmMail/blob/master/src/SlmMail/Factory/SesServiceFactory.php is that the `Aws\Sdk` service in the registry should return a `Aws\Ses\SesClient`. We can also simply list that as an instruction in the docs? That would remove the dependency altogether.

**Comment by snapshotpl** [comment]
In test you can see I downgrade composer to version 1. It's because `AwsModule` require outdated `laminas-dependency-plugin` https://github.com/aws/aws-sdk-php-zf2/pull/73

**Comment by snapshotpl** [comment]
Scrutinizer fail on phpcs, but it pass on travis

**Comment by roelvanduijnhoven** [comment]
@snapshotpl First of all: thank you for your effort. So the AWS package is optional now, great. But.. still it does not work on PHP8, right? So releasing this library for PHP 8.0 would still be kinda weird. Because we know the optional package will not work under PHP8. So I don't like this solution.

**Comment by roelvanduijnhoven** [comment]
I would say we either remove the dependency on https://github.com/aws/aws-sdk-php-zf2. Or we try to upgrade that version to PHP 8.0 by a PR.

**Comment by snapshotpl** [comment]
I think is ok now. This problem will be resolved when AWS will be upgraded. For me, when I doesn't use this dependency is win situation.

**Comment by roelvanduijnhoven** [comment]
@snapshotpl Thansk for your work allready :). That the dependency is optional is fine. But.. if the new PHP8 version of this repo does not allow the SES adapter to work, we cannot publish it in my opinion.

Valid options I see:

1. Remove the SES adapter altogether. 
2. Remove dependency on https://github.com/aws/aws-sdk-php-zf2 altogether, and depend on `Aws\Sdk` directly.
3. Wait or update the aws-sdk-php-zf2 package.

And really I would like to go with option 2 here. As we allready do so for 99% percent.

Would you be willing to help here? I'll push you in the right direction.

That I think is necessary is that we only need to update file https://github.com/JouwWeb/SlmMail/blob/master/src/SlmMail/Factory/SesServiceFactory.php. And make sure it will construct a client, and populate it with config parameters. Just like done in  https://github.com/aws/aws-sdk-php-zf2/blob/master/src/Factory/AwsFactory.php. And in much the same way as https://github.com/JouwWeb/SlmMail/blob/master/src/SlmMail/Factory/MandrillServiceFactory.php.

Psuedo code:
```php
namespace SlmMail\Factory;

use Aws\Sdk;
use Interop\Container\ContainerInterface;
use Laminas\ServiceManager\Factory\FactoryInterface;
use SlmMail\Service\SesService;

class SesServiceFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        $config = $container->get('config');

        if (!isset($config['slm_mail']['ses'])) {
            throw new RuntimeException(
                'Config for SES is not set, did you copy config file into your config/autoload folder ?'
            );
        }

        $sdk = new Sdk($config['slm_mail']['ses']);

        return new SesService($sdk->createSes());
    }
}
```

And add a mail/config/slm_mail.ses.php.dist file with:
``` 
<?php

return [
    'slm_mail' => [
        'ses' => [
            'credentials' => [
                'key'    => 'change_me',
                'secret' => 'change_me'
            ],
            'region'   => 'change_me',
            'version'  => 'latest',
            'DynamoDb' => [
                'region'  => 'another_region',
                'version' => 'latest'
            ]
        ]
    ]
];
```

And I think that should just work.

**Comment by snapshotpl** [comment]
Travis.org is down, probably need to migrate to Travis.com

**Comment by snapshotpl** [comment]
@roelvanduijnhoven I can't disable scrutinizer, it isnt defined in sources, you need to check it in repo settings.

**Comment by roelvanduijnhoven** [comment]
I think I removed it us now @snapshotpl.

**Comment by snapshotpl** [comment]
Great so if you are OK with this PR, then ship it!

**Comment by snapshotpl** [comment]
@roelvanduijnhoven all green!

**Comment by roelvanduijnhoven** [comment]
Nice work @snapshotpl! I released an alpha version: https://github.com/JouwWeb/SlmMail/releases/tag/v4.0-alpha.

Let's both test this version. Please ping me in 2 days, and tell me if it is still working. If so: I'll release 4.0 :)!

**Comment by snapshotpl** [comment]
@roelvanduijnhoven just released on production and works like harm! However mailgun adapter, not Aws.

**Comment by roelvanduijnhoven** [comment]
@snapshotpl I just released version 4.0. Thank you for all the effort :muscle:! I validated both Mandrill and Sparkpost are working fine :).

**Pull request merged**
